#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Copy private keys into the REPO with each deployment
echo -e "Copying private keys\n"
cp $DATA_DIR/keys_private_digitalocean.py $REPO_DIR/dcmetrometrics/keys/keys.py

# Install dependencies using pip
if [-e $REPO_DIR/requirements.txt]; then
  echo -e 'Installing dependencies using pip\n'
  source $PYTHON_DIR/virtenv/bin/activate
  pip install -r $REPO_DIR requirements.txt
fi

